# Define the docker hub image: https://hub.docker.com/_/node/
FROM node:14-alpine

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies and build
COPY package.json /usr/src/app
RUN npm install

# Bundle app source
COPY . /usr/src/app
RUN rm -f .env.production.local .env.development.local
RUN mv .env.docker.local .env.production.local
RUN npm run build

# clean
RUN npm prune --production
# Remove unused directories
RUN rm -rf ./src
RUN rm -rf ./build

EXPOSE 8080

# start app
CMD ["npm", "start"]