FROM node:14-alpine

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies and build
COPY package.json /usr/src/app
RUN npm install

# Bundle app source
COPY . /usr/src/app
RUN rm -f .env

EXPOSE 8080

# start app
CMD ["npm", "run", "serve"]